import enum

class ClientBlobBucket(enum.Enum):
  r"""
  GCS bucket references to where a client/frontend can upload blobs.
  These are mapped to the actual bucket via RegisterSingletonBucket.
  """
  CLIENT_BLOB_BUCKET_UNSPECIFIED = 0
  COMPETITION_DATA_FILES = 1
  COMPETITION_SUBMISSIONS = 2
  COMPETITION_SOLUTIONS = 3
  INBOX_FILES = 4
  FORUM_MESSAGE_ATTACHMENT_FILES = 5
  TEAM_MODEL_FILES = 6
  USER_CONTENT = 7
  DATASET_VERSION_FILES_V2 = 8
  KERNEL_SESSION_FILES = 9
  LEARN_CERTIFICATES = 10
  ORGANIZATIONS = 11
  KERNEL_BLOB = 12
  MODEL_INSTANCE_VERSION_FILES = 13
  DATABUNDLE_VERSION_CLOUD_VISION_OUTPUT = 14
  COMPETITION_CERTIFICATES = 15
  DOCKER_IMAGE_REQUIREMENTS_FILES = 16

