import enum

class TagType(enum.Enum):
  TAG_TYPE_UNSPECIFIED = 0
  TAG_TYPE_SEARCH_RESULT = 1
  TAG_TYPE_DATASET = 2
  TAG_TYPE_COMPETITION = 3
  TAG_TYPE_NOTEBOOK = 4
  TAG_TYPE_TASK = 5
  TAG_TYPE_MODEL = 6
  TAG_TYPE_BENCHMARK = 7
  TAG_TYPE_BENCHMARK_TASK = 8

class GetTagsByIdOrderBy(enum.Enum):
  GET_TAGS_BY_ID_ORDER_BY_UNSPECIFIED = 0
  GET_TAGS_BY_ID_ORDER_BY_REQUEST_ORDER = 1

