import enum

class NotificationType(enum.Enum):
  NOTIFICATION_TYPE_UNSPECIFIED = 0
  NOTIFICATION_TYPE_TOPIC_COMMENT = 1
  r"""
  values to 0, but should never be used
  Community notifications: 1-19
  """
  NOTIFICATION_TYPE_AT_MENTION = 2
  NOTIFICATION_TYPE_TOPIC_UPVOTE = 3
  NOTIFICATION_TYPE_NEW_TOPIC = 4
  NOTIFICATION_TYPE_NEW_KERNEL_VERSION = 5
  NOTIFICATION_TYPE_USER_NEW_TIER_ACHIEVED = 6
  NOTIFICATION_TYPE_NEW_MEDAL = 7
  NOTIFICATION_TYPE_USER_NEW_FOLLOWER = 8
  NOTIFICATION_TYPE_MODERATION_USER_PENALTY = 9
  NOTIFICATION_TYPE_NEW_BADGE = 10
  NOTIFICATION_TYPE_NOTEBOOK_FINISHED_RUNNING = 20
  """Notebooks notifications: 20-30"""
  NOTIFICATION_TYPE_NOTEBOOK_MADE_PUBLIC = 21
  NOTIFICATION_TYPE_NOTEBOOK_FORK_COUNT = 22
  NOTIFICATION_TYPE_NOTEBOOK_FEATURED = 23
  NOTIFICATION_TYPE_NOTEBOOK_VIEW_COUNT = 24
  NOTIFICATION_TYPE_NOTEBOOK_DISCUSSION_COUNT = 25
  NOTIFICATION_TYPE_NOTEBOOK_GITHUB_COMMIT = 26
  NOTIFICATION_TYPE_COMPETITION_DEADLINE_ONE_DAY = 101
  """Competitions notifications: 100-199"""
  NOTIFICATION_TYPE_COMPETITION_DEADLINE_ONE_WEEK = 102
  NOTIFICATION_TYPE_COMPETITION_FINALIZED = 103
  NOTIFICATION_TYPE_COMPETITION_TEAM_MERGE = 104
  NOTIFICATION_TYPE_COMPETITION_TEAM_INVITE = 105
  NOTIFICATION_TYPE_COMPETITION_NOTEBOOK_COUNT = 106
  NOTIFICATION_TYPE_COMPETITION_SUBMISSION_COUNT = 107
  NOTIFICATION_TYPE_COMPETITION_ENTRANT_COUNT = 108
  NOTIFICATION_TYPE_DATASET_NEW_PUBLIC_NOTEBOOK = 200
  """Datasets notifications: 200-225"""
  NOTIFICATION_TYPE_DATASET_NEW_TASK = 201
  NOTIFICATION_TYPE_DATASET_NEW_TASK_SOLUTION = 202
  NOTIFICATION_TYPE_DATASET_PUBLISHED = 203
  NOTIFICATION_TYPE_DATASET_UPLOADED = 204
  NOTIFICATION_TYPE_ACCOUNT_ALERT = 205
  NOTIFICATION_TYPE_DATASET_NOTEBOOK_COUNT = 206
  NOTIFICATION_TYPE_DATASET_PARTICIPATION_COUNT = 207
  NOTIFICATION_TYPE_DATASET_TRENDING = 208
  NOTIFICATION_TYPE_DATASET_VIEW_COUNT = 209
  NOTIFICATION_TYPE_DATASET_DOWNLOAD_COUNT = 210
  NOTIFICATION_TYPE_DATASET_SUGGESTION_REVIEWED = 213
  NOTIFICATION_TYPE_DATASET_SUGGESTION_CREATED = 215
  NOTIFICATION_TYPE_PENDING_FOR_TOO_LONG_LICENSE_AGREEMENT = 211
  r"""
  These aren't Datasets notifications, but the values are now
  persisted in the NotificationTypes table, so they can't change.
  """
  NOTIFICATION_TYPE_ORGANIZATION_NEW_MEMBER = 212
  NOTIFICATION_TYPE_ORGANIZATION_STATE_CHANGE = 214
  NOTIFICATION_TYPE_GROUP_INVITE = 226
  """Group and resource sharing notifications: 226-230"""
  NOTIFICATION_TYPE_RESOURCE_SHARED = 230
  NOTIFICATION_TYPE_BENCHMARK_RUN_COMPLETED = 231
  r"""
  Benchmark notifications: 231-235
  TODO: Rename to BENCHMARK_NEW_LEADERBOARD_ENTRY and
  BENCHMARK_NEW_MODEL_VERSION_AVAILABLE.
  """
  NOTIFICATION_TYPE_BENCHMARK_RUN_FAILED = 232
  NOTIFICATION_TYPE_BENCHMARK_LEADERBOARD_ENTRY = 233
  NOTIFICATION_TYPE_BENCHMARK_VERSION_PUBLISHED = 234
  NOTIFICATION_TYPE_BENCHMARK_NEW_MODEL_AVAILABLE = 235

class SettingsPageMessage(enum.Enum):
  r"""
  Key for messages to show on the settings page (to replace page messages)
  These aren't fully qualified because the transpiler is including the prefix
  on the enum value for some reason
  """
  SETTINGS_PAGE_MESSAGE_UNSPECIFIED = 0
  """Previous messages for now removed emails."""
  UNSUBSCRIBED_DATASET_UPDATES = 1
  UNSUBSCRIBED_PRIVATE_DATASET_SUMMARIES = 2
  UNSUBSCRIBED_GENERIC = 6
  UNSUBSCRIBED_COLLABORATION = 7
  UNSUBSCRIBE_LINK_FOR_OTHER_USER = 8
  INVALID_LINK = 9

class SubscribeState(enum.Enum):
  INVALID = 0
  UNSUBSCRIBE = 1
  SUBSCRIBE_SINGLE = 2
  """out of date, do not use except for back compat """
  SUBSCRIBE_ALL = 3
  FORUM_NEW_TOPICS = 10
  """Forums """
  FORUM_NEW_TOPICS_AND_COMMENTS = 11
  TOPIC_NEW_COMMENTS = 20
  """Topic """
  KERNEL_NEW_COMMENTS = 30
  """Kernels """
  KERNEL_NEW_COMMENTS_AND_VERSIONS = 31

class SubscriptionType(enum.Enum):
  SUBSCRIPTION_TYPE_NOT_APPLICABLE = 0
  SUBSCRIPTION_TYPE_FORUM_TOPIC = 1
  SUBSCRIPTION_TYPE_FORUM = 2
  SUBSCRIPTION_TYPE_KERNEL = 3
  SUBSCRIPTION_TYPE_GROUP = 4
  SUBSCRIPTION_TYPE_BENCHMARK = 5

class NotificationAggregationOption(enum.Enum):
  NOTIFICATION_AGGREGATION_OPTION_NO_AGGREGATION = 0
  NOTIFICATION_AGGREGATION_OPTION_DAILY = 1
  NOTIFICATION_AGGREGATION_OPTION_WEEKLY = 2

class NotificationDeliveryType(enum.Enum):
  NOTIFICATION_DELIVERY_TYPE_NONE = 0
  NOTIFICATION_DELIVERY_TYPE_WEB = 1
  NOTIFICATION_DELIVERY_TYPE_EMAIL = 2
  NOTIFICATION_DELIVERY_TYPE_BOTH = 3

class NotificationRelatedItemType(enum.Enum):
  NOTIFICATION_RELATED_ITEM_TYPE_UNSPECIFIED = 0
  NOTIFICATION_RELATED_ITEM_TYPE_FORUM_MESSAGE = 1
  NOTIFICATION_RELATED_ITEM_TYPE_KERNEL = 2
  NOTIFICATION_RELATED_ITEM_TYPE_KERNEL_RUN = 3
  NOTIFICATION_RELATED_ITEM_TYPE_USER_TIER_LOG = 4
  NOTIFICATION_RELATED_ITEM_TYPE_USER_MEDAL = 5
  NOTIFICATION_RELATED_ITEM_TYPE_COMPETITION = 6
  NOTIFICATION_RELATED_ITEM_TYPE_DATASET = 7
  NOTIFICATION_RELATED_ITEM_TYPE_TEAM = 8
  NOTIFICATION_RELATED_ITEM_TYPE_DATASET_TASK = 9
  NOTIFICATION_RELATED_ITEM_TYPE_DATASET_TASK_SOLUTION = 10
  NOTIFICATION_RELATED_ITEM_TYPE_USER = 11
  NOTIFICATION_RELATED_ITEM_TYPE_USER_PENALTY = 12
  NOTIFICATION_RELATED_ITEM_TYPE_ORGANIZATION = 13
  NOTIFICATION_RELATED_ITEM_TYPE_DATASET_SUGGESTION_BUNDLE = 14
  NOTIFICATION_RELATED_ITEM_TYPE_DATASET_VERSION = 15
  NOTIFICATION_RELATED_ITEM_TYPE_BADGE = 16
  NOTIFICATION_RELATED_ITEM_TYPE_GROUP = 17
  NOTIFICATION_RELATED_ITEM_TYPE_GROUP_INVITE = 18
  NOTIFICATION_RELATED_ITEM_TYPE_MODEL = 19
  NOTIFICATION_RELATED_ITEM_TYPE_BENCHMARK = 20
  NOTIFICATION_RELATED_ITEM_TYPE_BENCHMARK_RUN = 21
  NOTIFICATION_RELATED_ITEM_TYPE_BENCHMARK_MODEL_VERSION = 22
  NOTIFICATION_RELATED_ITEM_TYPE_BENCHMARK_VERSION = 23

