import enum

class GroupInviteState(enum.Enum):
  GROUP_INVITE_STATE_UNSPECIFIED = 0
  GROUP_INVITE_STATE_PENDING = 1
  GROUP_INVITE_STATE_ACCEPTED = 2
  """Invitation can be either accepted or rejected by the invitee."""
  GROUP_INVITE_STATE_REJECTED = 3
  GROUP_INVITE_STATE_WITHDRAWN = 4
  """Invitation withdrawn by a group admin."""

class GroupMembershipRole(enum.Enum):
  GROUP_MEMBERSHIP_ROLE_UNSPECIFIED = 0
  GROUP_MEMBERSHIP_ROLE_ADMIN = 1
  GROUP_MEMBERSHIP_ROLE_OWNER = 2
  GROUP_MEMBERSHIP_ROLE_MEMBER = 3

class ListUserManagedGroupInvitesOrderBy(enum.Enum):
  LIST_USER_MANAGED_GROUP_INVITES_ORDER_BY_CREATE_TIME = 0
  LIST_USER_MANAGED_GROUP_INVITES_ORDER_BY_INVITED_USERNAME = 1
  LIST_USER_MANAGED_GROUP_INVITES_ORDER_BY_INVITED_DISPLAY_NAME = 4
  LIST_USER_MANAGED_GROUP_INVITES_ORDER_BY_INVITED_BY_USERNAME = 2
  LIST_USER_MANAGED_GROUP_INVITES_ORDER_BY_INVITED_BY_DISPLAY_NAME = 5
  LIST_USER_MANAGED_GROUP_INVITES_ORDER_BY_GROUP_NAME = 3

class ListUserManagedGroupMembershipsOrderBy(enum.Enum):
  LIST_USER_MANAGED_GROUP_MEMBERSHIPS_ORDER_BY_USERNAME = 0
  LIST_USER_MANAGED_GROUP_MEMBERSHIPS_ORDER_BY_USER_DISPLAY_NAME = 3
  LIST_USER_MANAGED_GROUP_MEMBERSHIPS_ORDER_BY_ROLE = 1
  LIST_USER_MANAGED_GROUP_MEMBERSHIPS_ORDER_BY_JOIN_DATE = 2

class ListUserManagedGroupsOrderBy(enum.Enum):
  LIST_USER_MANAGED_GROUPS_ORDER_BY_RECENT = 0
  LIST_USER_MANAGED_GROUPS_ORDER_BY_NAME = 1

class OrderByDirection(enum.Enum):
  ASC = 0
  DESC = 1

class SynchronizedGroupProvider(enum.Enum):
  SYNCHRONIZED_GROUP_PROVIDER_UNSPECIFIED = 0
  SYNCHRONIZED_GROUP_PROVIDER_DYNAMIC = 1
  SYNCHRONIZED_GROUP_PROVIDER_GOOGLE = 2

