import enum

class ProfileArea(enum.Enum):
  PROFILE_AREA_UNSPECIFIED = 0
  PROFILE_AREA_HOME = 1
  PROFILE_AREA_COMPETITIONS = 2
  PROFILE_AREA_CODE = 3
  PROFILE_AREA_DISCUSSION = 4
  PROFILE_AREA_DATASETS = 5
  PROFILE_AREA_ACCOUNT = 6
  PROFILE_AREA_CONTACT = 7
  PROFILE_AREA_FOLLOWERS = 8
  PROFILE_AREA_FOLLOWING = 9
  PROFILE_AREA_GENIE = 10
  PROFILE_AREA_NOTIFICATIONS = 11
  PROFILE_AREA_NOTEBOOKS = 12
  PROFILE_AREA_MODELS = 13
  PROFILE_AREA_WRITEUPS = 14
  PROFILE_AREA_BENCHMARKS = 15

