import enum

class GatingAgreementModelsGatingStatus(enum.Enum):
  GATING_AGREEMENT_MODELS_GATING_STATUS_UNSPECIFIED = 0
  GATING_AGREEMENT_MODELS_GATING_STATUS_DISABLED = 1
  GATING_AGREEMENT_MODELS_GATING_STATUS_ENABLED = 2

class GatingAgreementRequestsExpiryStatus(enum.Enum):
  GATING_AGREEMENT_REQUESTS_EXPIRY_STATUS_UNSPECIFIED = 0
  GATING_AGREEMENT_REQUESTS_EXPIRY_STATUS_NOT_EXPIRED = 1
  GATING_AGREEMENT_REQUESTS_EXPIRY_STATUS_IS_EXPIRED = 2

class GatingAgreementRequestsReviewStatus(enum.Enum):
  GATING_AGREEMENT_REQUESTS_REVIEW_STATUS_UNSPECIFIED = 0
  GATING_AGREEMENT_REQUESTS_REVIEW_STATUS_PENDING = 1
  GATING_AGREEMENT_REQUESTS_REVIEW_STATUS_ACCEPTED = 2
  GATING_AGREEMENT_REQUESTS_REVIEW_STATUS_REJECTED = 3

class GatingAgreementsApprovalMethod(enum.Enum):
  GATING_AGREEMENT_APPROVAL_METHOD_UNSPECIFIED = 0
  GATING_AGREEMENT_APPROVAL_METHOD_MANUAL = 1
  GATING_AGREEMENT_APPROVAL_METHOD_AUTO = 2

class GatingUserConsentsOrderByDirection(enum.Enum):
  GATING_USER_CONSENTS_ORDER_BY_DIRECTION_ASC = 0
  GATING_USER_CONSENTS_ORDER_BY_DIRECTION_DESC = 1

class GetGatingUserConsentsOrderBy(enum.Enum):
  GET_GATING_USER_CONSENTS_ORDER_BY_REQUEST_TIME = 0
  GET_GATING_USER_CONSENTS_ORDER_BY_USERNAME = 1

class ListCompetitionModelInstancesOrderBy(enum.Enum):
  NUMBER_OF_UNIQUE_USERS = 0
  BEST_NOTEBOOK_SCORE = 1

class ListCompetitionModelInstancesTab(enum.Enum):
  LIST_COMPETITION_MODEL_INSTANCES_TAB_ALL = 0
  LIST_COMPETITION_MODEL_INSTANCES_TAB_YOUR_WORK = 1
  LIST_COMPETITION_MODEL_INSTANCES_TAB_SHARED_WITH_YOU = 2

class ListModelsOrderBy(enum.Enum):
  LIST_MODELS_ORDER_BY_UNSPECIFIED = 0
  LIST_MODELS_ORDER_BY_HOTNESS = 1
  LIST_MODELS_ORDER_BY_DOWNLOAD_COUNT = 2
  LIST_MODELS_ORDER_BY_VOTE_COUNT = 3
  LIST_MODELS_ORDER_BY_NOTEBOOK_COUNT = 4
  LIST_MODELS_ORDER_BY_PUBLISH_TIME = 5
  LIST_MODELS_ORDER_BY_CREATE_TIME = 6
  LIST_MODELS_ORDER_BY_UPDATE_TIME = 7
  LIST_MODELS_ORDER_BY_VIEW_TIME_DESC = 8

class ModelFramework(enum.Enum):
  MODEL_FRAMEWORK_UNSPECIFIED = 0
  MODEL_FRAMEWORK_TENSOR_FLOW_1 = 1
  MODEL_FRAMEWORK_TENSOR_FLOW_2 = 2
  MODEL_FRAMEWORK_TF_LITE = 3
  MODEL_FRAMEWORK_TF_JS = 4
  MODEL_FRAMEWORK_PY_TORCH = 5
  MODEL_FRAMEWORK_JAX = 6
  MODEL_FRAMEWORK_FLAX = 14
  MODEL_FRAMEWORK_PAX = 15
  MODEL_FRAMEWORK_MAX_TEXT = 17
  MODEL_FRAMEWORK_GEMMA_CPP = 18
  MODEL_FRAMEWORK_GGML = 19
  MODEL_FRAMEWORK_GGUF = 21
  MODEL_FRAMEWORK_CORAL = 7
  MODEL_FRAMEWORK_SCIKIT_LEARN = 8
  MODEL_FRAMEWORK_MXNET = 9
  MODEL_FRAMEWORK_ONNX = 10
  MODEL_FRAMEWORK_KERAS = 11
  MODEL_FRAMEWORK_TRANSFORMERS = 16
  MODEL_FRAMEWORK_API = 12
  MODEL_FRAMEWORK_OTHER = 13
  MODEL_FRAMEWORK_TENSOR_RT_LLM = 20
  MODEL_FRAMEWORK_TRITON = 22

class ModelInstanceType(enum.Enum):
  MODEL_INSTANCE_TYPE_UNSPECIFIED = 0
  MODEL_INSTANCE_TYPE_BASE_MODEL = 1
  MODEL_INSTANCE_TYPE_KAGGLE_VARIANT = 2
  MODEL_INSTANCE_TYPE_EXTERNAL_VARIANT = 3

class ModelLicense(enum.Enum):
  UNSPECIFIED = 0
  CC0 = 1
  """Enum int values taken from dbo.Licenses"""
  APACHE2 = 30
  MIT = 31
  BSD = 32
  RAIL_M = 36
  OTHER = 12

class ModelOwnerType(enum.Enum):
  MODEL_OWNER_TYPE_UNSPECIFIED = 0
  MODEL_OWNER_TYPE_USER = 1
  MODEL_OWNER_TYPE_ORGANIZATION = 2
  MODEL_OWNER_TYPE_HUGGING_FACE = 3

class ModelTab(enum.Enum):
  MODEL_TAB_MODEL_CARD = 0
  MODEL_TAB_CODE = 1
  MODEL_TAB_DISCUSSION = 2
  MODEL_TAB_ADMIN = 3
  MODEL_TAB_SETTINGS = 4
  MODEL_TAB_COMPETITIONS = 5

class ModelVersionLinkType(enum.Enum):
  MODEL_VERSION_LINK_TYPE_UNSPECIFIED = 0
  MODEL_VERSION_LINK_TYPE_VERTEX_OPEN = 1
  MODEL_VERSION_LINK_TYPE_VERTEX_DEPLOY = 2

class SigstoreState(enum.Enum):
  SIGSTORE_STATE_UNSPECIFIED = 0
  SIGSTORE_STATE_NONE = 1
  SIGSTORE_STATE_PENDING = 2
  SIGSTORE_STATE_SIGNED = 3
  """but the contents is unverified by kaggle."""
  SIGSTORE_STATE_FAILED = 4

class ModelCreateReferrer(enum.Enum):
  MODEL_CREATE_REFERRER_UNSPECIFIED = 0
  MODEL_CREATE_REFERRER_WEB_UI = 1
  MODEL_CREATE_REFERRER_API_KAGGLEHUB = 2
  """These values are inferred from the request user agent in API create calls."""
  MODEL_CREATE_REFERRER_API_PY_CLIENT = 3
  MODEL_CREATE_REFERRER_API_UNKNOWN = 4
  r"""
  If the ModelApiService is called but the referrer can't be inferred from
  the user agent.
  """
  MODEL_CREATE_REFERRER_TFHUB_INGESTOR = 5
  MODEL_CREATE_REFERRER_API_KAGGLEHUB_KERAS = 6
  """Created via kagglehub.keras API."""
  MODEL_CREATE_REFERRER_WEB_UI_COPY = 7
  """Created by copying a version from another model."""
  MODEL_CREATE_REFERRER_KERNEL_SESSION_END = 8
  """Automatically created from kernel session end"""
  MODEL_CREATE_REFERRER_API_KAGGLEHUB_TORCHTUNE = 9
  """Created via torch tune in kagglehub."""

class ModelInstanceActivityType(enum.Enum):
  MODEL_INSTANCE_ACTIVITY_TYPE_UNSPECIFIED = 0
  MODEL_INSTANCE_ACTIVITY_TYPE_CREATE = 1
  MODEL_INSTANCE_ACTIVITY_TYPE_NEW_VERSION = 2
  MODEL_INSTANCE_ACTIVITY_TYPE_REMOVE = 3
  MODEL_INSTANCE_ACTIVITY_TYPE_REMOVE_VERSION = 4

class ModelInstanceSchemaDiffAction(enum.Enum):
  MODEL_INSTANCE_SCHEMA_DIFF_ACTION_ADD = 0
  MODEL_INSTANCE_SCHEMA_DIFF_ACTION_DELETE = 1
  MODEL_INSTANCE_SCHEMA_DIFF_ACTION_MODIFY_FILE = 2

class ModelInstanceSchemaDiffContainerLevel(enum.Enum):
  MODEL_INSTANCE_SCHEMA_DIFF_CONTAINER_LEVEL_UNSPECIFIED = 0
  MODEL_INSTANCE_SCHEMA_DIFF_CONTAINER_LEVEL_MODEL_INSTANCE = 1
  MODEL_INSTANCE_SCHEMA_DIFF_CONTAINER_LEVEL_FILE = 2
  r"""
  For now, only detect file-level changes. If we discover that models contain
  tabular data, we can support it later
  """

class ModelProxyQuotaRefillPeriod(enum.Enum):
  """How often a quota is refilled."""
  REFILL_PERIOD_UNSPECIFIED = 0
  DAILY = 1
  MONTHLY = 2

class UnifiedModelGatingStatus(enum.Enum):
  """TODO(b/379918675) Migrate to UnifiedModelGatingStatus."""
  UNIFIED_MODEL_GATING_STATUS_UNSPECIFIED = 0
  UNIFIED_MODEL_GATING_STATUS_MISSING = 1
  UNIFIED_MODEL_GATING_STATUS_REJECTED = 2
  UNIFIED_MODEL_GATING_STATUS_PENDING = 3
  UNIFIED_MODEL_GATING_STATUS_ACCEPTED = 4

