import enum

class CommentAuthorType(enum.Enum):
  COMMENT_AUTHOR_TYPE_UNSPECIFIED = 0
  r"""
  Default value of author type makes no claim about what type of author it
  is, and nothing special should be shown.
  """
  HOST = 1
  DATASET_CREATOR = 2
  TOPIC = 3
  COMMENT = 4
  ADMIN = 5
  MODEL_CREATOR = 6
  JUDGE = 7

class CommentListSortBy(enum.Enum):
  COMMENT_LIST_SORT_BY_UNSPECIFIED = 0
  COMMENT_LIST_SORT_BY_HOT = 1
  COMMENT_LIST_SORT_BY_NEW = 2
  COMMENT_LIST_SORT_BY_OLD = 3
  COMMENT_LIST_SORT_BY_TOP = 4

class EmojiReaction(enum.Enum):
  EMOJI_REACTION_UNSPECIFIED = 0
  THANK_YOU = 1
  YAY = 2
  LOVE = 3
  KAGGLE = 4
  FUNNY = 5
  SURPRISE = 6

class FlagReason(enum.Enum):
  FLAG_REASON_UNSPECIFIED = 0
  FLAG_REASON_OTHER = 1
  FLAG_REASON_SPAM = 2
  FLAG_REASON_PLAGIARISM = 3
  FLAG_REASON_VOTE_MANIPULATION = 4
  FLAG_REASON_ABUSIVE = 5
  FLAG_REASON_PRIVACY_VIOLATION = 6
  FLAG_REASON_COPYRIGHT_VIOLATION = 7
  FLAG_REASON_UPVOTE_BEGGING = 8

class FollowUpStatus(enum.Enum):
  NONE = 0
  IN_PROGRESS = 1
  DONE = 2

class TopicListAuthor(enum.Enum):
  TOPIC_LIST_AUTHOR_UNSPECIFIED = 0
  TOPIC_LIST_AUTHOR_ADMIN = 1

class TopicListCategory(enum.Enum):
  TOPIC_LIST_CATEGORY_UNSPECIFIED = 0
  TOPIC_LIST_CATEGORY_ALL = 1
  TOPIC_LIST_CATEGORY_FORUMS = 2
  TOPIC_LIST_CATEGORY_COMPETITIONS = 3
  TOPIC_LIST_CATEGORY_DATASETS = 4
  TOPIC_LIST_CATEGORY_COMPETITION_WRITE_UPS = 5
  TOPIC_LIST_CATEGORY_MODELS = 6
  TOPIC_LIST_CATEGORY_BENCHMARKS = 7

class TopicListGroup(enum.Enum):
  TOPIC_LIST_GROUP_UNSPECIFIED = 0
  TOPIC_LIST_GROUP_ALL = 1
  TOPIC_LIST_GROUP_OWNED = 2
  TOPIC_LIST_GROUP_UPVOTED = 3
  TOPIC_LIST_GROUP_BOOKMARKED = 4
  TOPIC_LIST_GROUP_MY_ACTIVITY = 5
  TOPIC_LIST_GROUP_DRAFTS = 6

class TopicListMyActivity(enum.Enum):
  TOPIC_LIST_MY_ACTIVITY_UNSPECIFIED = 0
  TOPIC_LIST_MY_ACTIVITY_PUBLISHED = 1
  TOPIC_LIST_MY_ACTIVITY_COMMENTED = 2
  TOPIC_LIST_MY_ACTIVITY_VIEWED = 3

class TopicListRecency(enum.Enum):
  TOPIC_LIST_RECENCY_UNSPECIFIED = 0
  TOPIC_LIST_RECENCY_LAST_30_DAYS = 1
  TOPIC_LIST_RECENCY_LAST_7_DAYS = 2
  TOPIC_LIST_RECENCY_TODAY = 3

class TopicListSortBy(enum.Enum):
  TOPIC_LIST_SORT_BY_UNSPECIFIED = 0
  TOPIC_LIST_SORT_BY_HOT = 1
  TOPIC_LIST_SORT_BY_TOP = 2
  TOPIC_LIST_SORT_BY_NEW = 3
  TOPIC_LIST_SORT_BY_RECENT = 4
  TOPIC_LIST_SORT_BY_ACTIVE = 5
  TOPIC_LIST_SORT_BY_RELEVANCE = 6

class CommentListFilter(enum.Enum):
  ALL = 0
  KERNEL_VERSION = 1

class ForumMessageSettings(enum.Enum):
  FORUM_MESSAGE_SETTINGS_UNSPECIFIED = 0
  IS_PRIVATE = 1

class ForumSettings(enum.Enum):
  FORUM_SETTINGS_IS_READ_ONLY = 0

class ForumTopicSettings(enum.Enum):
  FORUM_TOPIC_SETTINGS_IS_READ_ONLY = 0
  IS_STICKY = 1

