import enum

class CompetitionDatabundleType(enum.Enum):
  COMPETITION_DATABUNDLE_TYPE_UNSPECIFIED = 0
  COMPETITION_DATABUNDLE_TYPE_PUBLIC = 1
  COMPETITION_DATABUNDLE_TYPE_RERUN = 2

class HackathonTrackPrizeType(enum.Enum):
  HACKATHON_TRACK_PRIZE_TYPE_UNSPECIFIED = 0
  HACKATHON_TRACK_PRIZE_TYPE_KUDOS = 1
  HACKATHON_TRACK_PRIZE_TYPE_NON_MONETARY = 2
  HACKATHON_TRACK_PRIZE_TYPE_MONETARY = 3

class HostSegment(enum.Enum):
  r"""
  NOTE: Keep in Sync with Kaggle.Entities.HostSegment until migrated! Also keep
  the comment in
  competition_service.ListCompetitionsRequest.Selector.host_segment_id_filter
  up to date
  """
  HOST_SEGMENT_UNSPECIFIED = 0
  HOST_SEGMENT_FEATURED = 1
  HOST_SEGMENT_GETTING_STARTED = 5
  HOST_SEGMENT_MASTERS = 6
  HOST_SEGMENT_PLAYGROUND = 8
  HOST_SEGMENT_RECRUITMENT = 3
  HOST_SEGMENT_RESEARCH = 2
  HOST_SEGMENT_COMMUNITY = 10
  HOST_SEGMENT_ANALYTICS = 11

class CompetitionPrivacy(enum.Enum):
  COMPETITION_PRIVACY_UNSPECIFIED = 0
  PUBLIC = 1
  LIMITED = 2
  PRIVATE = 3

