from google.protobuf.field_mask_pb2 import FieldMask
from kagglesdk.kaggle_object import *
from kagglesdk.security.types.authentication import AuthorizationScope
from kagglesdk.security.types.security_types import OAuthClient
from typing import Optional, List

class CreateOAuthClientRequest(KaggleObject):
  r"""
  Attributes:
    client (OAuthClient)
  """

  def __init__(self):
    self._client = None
    self._freeze()

  @property
  def client(self) -> Optional['OAuthClient']:
    return self._client

  @client.setter
  def client(self, client: Optional['OAuthClient']):
    if client is None:
      del self.client
      return
    if not isinstance(client, OAuthClient):
      raise TypeError('client must be of type OAuthClient')
    self._client = client


class DeleteOAuthClientRequest(KaggleObject):
  r"""
  Attributes:
    id (int)
  """

  def __init__(self):
    self._id = 0
    self._freeze()

  @property
  def id(self) -> int:
    return self._id

  @id.setter
  def id(self, id: int):
    if id is None:
      del self.id
      return
    if not isinstance(id, int):
      raise TypeError('id must be of type int')
    self._id = id


class FinalizeOAuthFlowRequest(KaggleObject):
  r"""
  Attributes:
    code (str)
      Temporary OAuth code that was generated by the backend based on OAuth
      parameters passed to the '/api/v1/oauth2/authorize' (StartOAuthFlowRequest)
      endpoint. This is also known as OAuth flow token.
    authorization_scopes (AuthorizationScope)
      Set of authorization scopes to further restrict the OAuth token.
  """

  def __init__(self):
    self._code = ""
    self._authorization_scopes = []
    self._freeze()

  @property
  def code(self) -> str:
    r"""
    Temporary OAuth code that was generated by the backend based on OAuth
    parameters passed to the '/api/v1/oauth2/authorize' (StartOAuthFlowRequest)
    endpoint. This is also known as OAuth flow token.
    """
    return self._code

  @code.setter
  def code(self, code: str):
    if code is None:
      del self.code
      return
    if not isinstance(code, str):
      raise TypeError('code must be of type str')
    self._code = code

  @property
  def authorization_scopes(self) -> Optional[List[Optional['AuthorizationScope']]]:
    """Set of authorization scopes to further restrict the OAuth token."""
    return self._authorization_scopes

  @authorization_scopes.setter
  def authorization_scopes(self, authorization_scopes: Optional[List[Optional['AuthorizationScope']]]):
    if authorization_scopes is None:
      del self.authorization_scopes
      return
    if not isinstance(authorization_scopes, list):
      raise TypeError('authorization_scopes must be of type list')
    if not all([isinstance(t, AuthorizationScope) for t in authorization_scopes]):
      raise TypeError('authorization_scopes must contain only items of type AuthorizationScope')
    self._authorization_scopes = authorization_scopes


class FinalizeOAuthFlowResponse(KaggleObject):
  r"""
  Attributes:
    redirect_uri (str)
      Redirect URL to flow initiator's auth endpoint specified in
      '/api/v1/oauth2/authorize' (StartOAuthFlowRequest). It will contain the
      generated code as an arguments if the authentication is successful.
      Example:
      https://dataverse.org/auth/kaggle?code=808f9afcabb3489a8b30353a8ae4dc4b
  """

  def __init__(self):
    self._redirect_uri = ""
    self._freeze()

  @property
  def redirect_uri(self) -> str:
    r"""
    Redirect URL to flow initiator's auth endpoint specified in
    '/api/v1/oauth2/authorize' (StartOAuthFlowRequest). It will contain the
    generated code as an arguments if the authentication is successful.
    Example:
    https://dataverse.org/auth/kaggle?code=808f9afcabb3489a8b30353a8ae4dc4b
    """
    return self._redirect_uri

  @redirect_uri.setter
  def redirect_uri(self, redirect_uri: str):
    if redirect_uri is None:
      del self.redirect_uri
      return
    if not isinstance(redirect_uri, str):
      raise TypeError('redirect_uri must be of type str')
    self._redirect_uri = redirect_uri


class GetOAuthClientRequest(KaggleObject):
  r"""
  Attributes:
    id (int)
  """

  def __init__(self):
    self._id = 0
    self._freeze()

  @property
  def id(self) -> int:
    return self._id

  @id.setter
  def id(self, id: int):
    if id is None:
      del self.id
      return
    if not isinstance(id, int):
      raise TypeError('id must be of type int')
    self._id = id


class GetOAuthFlowInfoRequest(KaggleObject):
  r"""
  Attributes:
    code (str)
      Temporary OAuth code that was generated by the backend based on OAuth
      parameters passed to the '/api/v1/oauth2/authorize' (StartOAuthFlowRequest)
      endpoint. This is also known as OAuth flow token.
  """

  def __init__(self):
    self._code = ""
    self._freeze()

  @property
  def code(self) -> str:
    r"""
    Temporary OAuth code that was generated by the backend based on OAuth
    parameters passed to the '/api/v1/oauth2/authorize' (StartOAuthFlowRequest)
    endpoint. This is also known as OAuth flow token.
    """
    return self._code

  @code.setter
  def code(self, code: str):
    if code is None:
      del self.code
      return
    if not isinstance(code, str):
      raise TypeError('code must be of type str')
    self._code = code


class ListOAuthClientsRequest(KaggleObject):
  r"""
  """

  pass

class ListOAuthClientsResponse(KaggleObject):
  r"""
  Attributes:
    clients (OAuthClient)
  """

  def __init__(self):
    self._clients = []
    self._freeze()

  @property
  def clients(self) -> Optional[List[Optional['OAuthClient']]]:
    return self._clients

  @clients.setter
  def clients(self, clients: Optional[List[Optional['OAuthClient']]]):
    if clients is None:
      del self.clients
      return
    if not isinstance(clients, list):
      raise TypeError('clients must be of type list')
    if not all([isinstance(t, OAuthClient) for t in clients]):
      raise TypeError('clients must contain only items of type OAuthClient')
    self._clients = clients


class OAuthFlowInfo(KaggleObject):
  r"""
  Attributes:
    client_name (str)
      Name of the OAuth client to show to the user so they know who is requesting
      access to Kaggle on their behalf.
    redirect_uri (str)
      Redirect URL of the flow initiator to redirect the user.
    authorization_scopes (AuthorizationScope)
      Authorization scopes that apply to this OAuth flow. Refresh and access
      tokens generated when this flow ends will be restricted to these scopes.
      These are specified by the flow initiator through the 'scope' parameter to
      the '/api/v1/oauth/authorize' endpoint.
  """

  def __init__(self):
    self._client_name = ""
    self._redirect_uri = ""
    self._authorization_scopes = []
    self._freeze()

  @property
  def client_name(self) -> str:
    r"""
    Name of the OAuth client to show to the user so they know who is requesting
    access to Kaggle on their behalf.
    """
    return self._client_name

  @client_name.setter
  def client_name(self, client_name: str):
    if client_name is None:
      del self.client_name
      return
    if not isinstance(client_name, str):
      raise TypeError('client_name must be of type str')
    self._client_name = client_name

  @property
  def redirect_uri(self) -> str:
    """Redirect URL of the flow initiator to redirect the user."""
    return self._redirect_uri

  @redirect_uri.setter
  def redirect_uri(self, redirect_uri: str):
    if redirect_uri is None:
      del self.redirect_uri
      return
    if not isinstance(redirect_uri, str):
      raise TypeError('redirect_uri must be of type str')
    self._redirect_uri = redirect_uri

  @property
  def authorization_scopes(self) -> Optional[List[Optional['AuthorizationScope']]]:
    r"""
    Authorization scopes that apply to this OAuth flow. Refresh and access
    tokens generated when this flow ends will be restricted to these scopes.
    These are specified by the flow initiator through the 'scope' parameter to
    the '/api/v1/oauth/authorize' endpoint.
    """
    return self._authorization_scopes

  @authorization_scopes.setter
  def authorization_scopes(self, authorization_scopes: Optional[List[Optional['AuthorizationScope']]]):
    if authorization_scopes is None:
      del self.authorization_scopes
      return
    if not isinstance(authorization_scopes, list):
      raise TypeError('authorization_scopes must be of type list')
    if not all([isinstance(t, AuthorizationScope) for t in authorization_scopes]):
      raise TypeError('authorization_scopes must contain only items of type AuthorizationScope')
    self._authorization_scopes = authorization_scopes


class UpdateOAuthClientRequest(KaggleObject):
  r"""
  Attributes:
    client (OAuthClient)
    update_mask (FieldMask)
  """

  def __init__(self):
    self._client = None
    self._update_mask = None
    self._freeze()

  @property
  def client(self) -> Optional['OAuthClient']:
    return self._client

  @client.setter
  def client(self, client: Optional['OAuthClient']):
    if client is None:
      del self.client
      return
    if not isinstance(client, OAuthClient):
      raise TypeError('client must be of type OAuthClient')
    self._client = client

  @property
  def update_mask(self) -> FieldMask:
    return self._update_mask

  @update_mask.setter
  def update_mask(self, update_mask: FieldMask):
    if update_mask is None:
      del self.update_mask
      return
    if not isinstance(update_mask, FieldMask):
      raise TypeError('update_mask must be of type FieldMask')
    self._update_mask = update_mask


CreateOAuthClientRequest._fields = [
  FieldMetadata("client", "client", "_client", OAuthClient, None, KaggleObjectSerializer()),
]

DeleteOAuthClientRequest._fields = [
  FieldMetadata("id", "id", "_id", int, 0, PredefinedSerializer()),
]

FinalizeOAuthFlowRequest._fields = [
  FieldMetadata("code", "code", "_code", str, "", PredefinedSerializer()),
  FieldMetadata("authorizationScopes", "authorization_scopes", "_authorization_scopes", AuthorizationScope, [], ListSerializer(KaggleObjectSerializer())),
]

FinalizeOAuthFlowResponse._fields = [
  FieldMetadata("redirectUri", "redirect_uri", "_redirect_uri", str, "", PredefinedSerializer()),
]

GetOAuthClientRequest._fields = [
  FieldMetadata("id", "id", "_id", int, 0, PredefinedSerializer()),
]

GetOAuthFlowInfoRequest._fields = [
  FieldMetadata("code", "code", "_code", str, "", PredefinedSerializer()),
]

ListOAuthClientsRequest._fields = []

ListOAuthClientsResponse._fields = [
  FieldMetadata("clients", "clients", "_clients", OAuthClient, [], ListSerializer(KaggleObjectSerializer())),
]

OAuthFlowInfo._fields = [
  FieldMetadata("clientName", "client_name", "_client_name", str, "", PredefinedSerializer()),
  FieldMetadata("redirectUri", "redirect_uri", "_redirect_uri", str, "", PredefinedSerializer()),
  FieldMetadata("authorizationScopes", "authorization_scopes", "_authorization_scopes", AuthorizationScope, [], ListSerializer(KaggleObjectSerializer())),
]

UpdateOAuthClientRequest._fields = [
  FieldMetadata("client", "client", "_client", OAuthClient, None, KaggleObjectSerializer()),
  FieldMetadata("updateMask", "update_mask", "_update_mask", FieldMask, None, FieldMaskSerializer()),
]

